[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["mzmt <mrcrius1355@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.0.0", reatures = ["postgres"] }
dotenv = "0.9.0"
